BlockchainApp/urls.py
from django.urls import path
from . import views
app_name="BlockchainApp"

urlpatterns = [
    path('blockchain/',views.route_blockchain,name='route_blockchain'),
    path('blockchain/range/',views.route_blockchain_range,name='route_blockchain_range'),
    path('blockchain/length/',views.route_blockchain_length,name='route_blockchain_length'),
    path('blockchain/mine/',views.route_blockchain_mine,name='route_blockchain_mine'),
    path('wallet/transact/',views.route_wallet_transact,name='route_wallet_transact'),
    path('transactions/',views.route_transactions,name='route_transactions'),


]

CandidateApp/urls.py
from django.urls import path
from . import views
app_name="CandidateApp"

urlpatterns = [
    path('ec-login/',views.ec_login,name='ec-login'),
    path('ec-login-success/',views.ec_login_success,name='ec-login-success'),
    path('ec-home/',views.ec_home,name='ec-home'),
    path('ec-logout/', views.ec_logout, name='ec-officer-logout'),
    path('candidate-register-home', views.candidate_register_home, name='candidate-register-home'),
    path('candidate-register-success', views.candidate_register_success, name='candidate-register-success')
]

CryptoBallotsProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register-user/', include('RegistrationApp.urls')),
    path('voter-profile/', include('VoterProfileApp.urls')),
    path('candidate/', include('CandidateApp.urls')),
    path('home/', include('CryptoBallotsHomeApp.urls')),
    path('voting-window/',include('VotingApp.urls')),
    path('blockchain/',include('BlockchainApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

RegistrationApp/urls.py
from django.urls import path
from . import views

app_name="RegistrationApp"

urlpatterns = [
    path('register/',views.home,name="home"),
    path('user-register-success', views.user_register_success, name="user-register-success"),
    path('login/',views.login_window,name="login"),
    path('officer-login-success/', views.officer_login_success, name="officer-login-success"),
    path('officer-logout/', views.officer_logout, name="officer-logout"),
    path('ok-clicked/',views.ok,name="ok"),
    path('update-window/',views.update_window,name="update-window"),
    path('save-update-details/', views.save_update_details, name="save-update-details"),

    path('user_register_window/', views.user_register_window, name = 'user_register_window'),
	path('success/', views.success, name = 'success'),
]

VoterProfileApp/urls.py
from django.urls import path
from . import views

app_name="VoterProfileApp"

urlpatterns = [
    path('login-page/',views.login_page,name="login"),
    path('see/',views.voter_profile,name="voter-profile"),
    path('voter-login-success/',views.voter_login_success,name="voter-login-success"),
    path('voter-logout/', views.voter_logout, name="voter-logout"),
    path('changepassword/', views.changepassword, name="changepassword"),
    path('changepassword-submit/',views.changepassword_submit,name="changepassword-submit"),
    path('forgot-password/',views.forgot_password,name="forgot-password"),
    path('check-forgot-password/',views.check_forgot_password,name="check-forgot-password"),
    ]

VotingApp/urls.py
from django.urls import path
from . import views

app_name="VotingApp"

urlpatterns = [
    path('login/',views.loginn,name='login'),
    path('home/',views.home,name='home'),
    path('logout/',views.officer_logout,name='logout'),
    path('officer-login-success/',views.officer_login_success,name='officer-login-success'),
    path('display-candidates/', views.display_candidates, name='display-candidates')
]

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>
  <body>
    {% block content %}

    {% endblock %}
  </body>
</html>

templates/candidate-register-home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" style="font-weight: 900;">Candidate's Registration</a>

    <a class="btn btn-danger" href="{% url 'RegistrationApp:officer-logout' %}">Logout</a>
</nav>

<div style="padding: 20px;width: 800px;background-color: #fe6e00;display: block;margin: auto;
  margin-top: 80px">
  <h1 style="color: white;text-align: center">Registration</h1>
  <form method="post" action="{% url 'CandidateApp:candidate-register-success' %}">
    {% csrf_token %}
    <input type="text" class="form-control" placeholder="Aadhar Number" name="aadhar-no">
    <input type="text" class="form-control" placeholder="Candidate's Party" name="party">
    <input type="text" class="form-control" placeholder="Standing Seat Pincode" name="standing-pincode">
    <input type="submit"  style="display: block;margin: auto;margin-top: 10px" class="btn btn-success">
  </form>
</div>
{% endblock %}

templates/changepassword-result.html
{{mssg}}

templates/changepassword.html
{% extends 'base.html' %}
{% block content %}

<div style="padding: 20px;width: 300px;background-color: #fe6e00;display: block;margin: auto;
  margin-top: 250px">
  <h1 style="color: white;text-align: center">Change Password</h1>
  <form method="post" action="{% url 'VoterProfileApp:changepassword-submit' %}">
    {% csrf_token %}
    <input type="password" class="form-control" placeholder="CurrentPassword" name="currentpassword">
    <input type="password" class="form-control" placeholder="NewPassword" name="newpassword">
    <input type="password" class="form-control" placeholder="ConfirmPassword" name="confirmpassword">
    <input type="submit" style="display: block;margin: auto;margin-top: 10px" class="btn btn-success" >
  </form>
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

</div>


{% endblock %}

templates/ex.html
{% load static %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="aadhar_no" value="{{aadhar_no}}" hidden>
  <input type="submit" name="picture_url" value="Take Picture">
</form>
<img src="{{image.url}}" alt="dp">

templates/forgot-password.html
{% extends 'base.html' %}
{% block content %}

  <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" style="font-weight: 900;">Forgot password</a>
      <a class="btn btn-success" href="{% url 'VoterProfileApp:login' %}">Back To Login</a>
  </nav>
  <div style="padding: 20px;width: 300px;background-color: #fe6e00;display: block;margin: auto;
    margin-top: 250px">
    <h1 style="color: white;text-align: center">Set new password</h1>
    <form method="post" action="{% url 'VoterProfileApp:check-forgot-password' %}">
      {% csrf_token %}
      <input type="text" style="margin-bottom: 15px" class="form-control" placeholder="aadhar_no" name="aadhar_no">
      <input type="password" class="form-control" placeholder="voter_id" name="voter_id">
      <input type="password" class="form-control" placeholder="newpassword" name="newpassword">
      <input type="submit" style="display: block;margin: auto;margin-top: 10px" class="btn btn-success" value="Confirm" >
    </form>
  </div>
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}

<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" style="font-weight: 900;">Home Page</a>
    <a class="btn btn-danger" href="{% url 'RegistrationApp:login' %}">Voter's Registration</a>
    <a class="btn btn-danger" href="{% url 'VoterProfileApp:login' %}">Voter's Profile</a>
    <a class="btn btn-danger" href="{% url 'CandidateApp:ec-login' %}">Election Commission</a>
    <a class="btn btn-danger" href="{% url 'VotingApp:login' %}">Voting Window</a>
</nav>

{% endblock %}

templates/registration-home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" style="font-weight: 900;">Voter's Registration</a>
    <a class="btn btn-danger" href="{% url 'RegistrationApp:update-window' %}">Update</a>
    <a class="btn btn-danger" href="{% url 'RegistrationApp:officer-logout' %}">Logout</a>
</nav>

<div style="padding: 20px;width: 800px;background-color: #fe6e00;display: block;margin: auto;
  margin-top: 80px">
  <h1 style="color: white;text-align: center">Registration</h1>
  <form method="post" action="{% url 'RegistrationApp:user-register-success' %}">
    {% csrf_token %}
    <input type="text" style="margin-bottom: 15px" class="form-control" placeholder="Full Name" name="full-name">
    <input type="text" class="form-control" placeholder="Aadhar Number" name="aadhar-no">
    <input type="date" style="margin-bottom: 15px" class="form-control" placeholder="Date Of Birth" name="dob">
    <input type="text" class="form-control" placeholder="Phone Number" name="phone-no">
    <input type="text" style="margin-bottom: 15px" class="form-control" placeholder="Country" name="country">
    <input type="text" class="form-control" placeholder="State" name="state">
    <input type="text" style="margin-bottom: 15px" class="form-control" placeholder="City" name="city">
    <input type="text" class="form-control" placeholder="Taluka" name="taluka">
    <input type="text" class="form-control" placeholder="Pincode" name="pincode">
    <input type="text" class="form-control" placeholder="constituency" name="constituency">
    <input type="file" id="image" name="image" accept="image/*">
    <input type="submit" style="display: block;margin: auto;margin-top: 10px" class="btn btn-success">
  </form>
</div>
{% endblock %}

templates/registration-login.html


{% extends 'base.html' %}
{% block content %}

<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" style="font-weight: 900;">Registration Officer Login</a>

    <a class="btn btn-success" href="{% url 'CryptoBallotsHomeApp:home' %}">Home</a>

</nav>
<div style="padding: 20px;width: 300px;background-color: #fe6e00;display: block;margin: auto;
  margin-top: 250px">
  <h1 style="color: white;text-align: center">Officer Login</h1>
  <form method="post" action="{% url 'RegistrationApp:officer-login-success' %}">
    {% csrf_token %}
    <input type="text" style="margin-bottom: 15px" class="form-control" placeholder="OfficerID" name="officer-id">
    <input type="password" class="form-control" placeholder="password" name="password">
    <input type="submit" style="display: block;margin: auto;margin-top: 10px" class="btn btn-success" >
  </form>
</div>

{% endblock %}

templates/try.html
<h1>{{bc}}</h1>

templates/update.html
{% extends 'base.html' %}
{% block content %}
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" style="font-weight: 900;">Voter's Profile Update</a>
    <a class="btn btn-danger" href="{% url 'RegistrationApp:home' %}">Registration Page</a>
</nav>

<div style="padding: 20px;width: 800px;background-color: #fe6e00;display: block;margin: auto;
  margin-top: 80px">
  <h1 style="color: white;text-align: center">Update Profile</h1>


  {% if update_flag %}
  <form method="post" action="{% url 'RegistrationApp:ok' %}">
    {% csrf_token %}
    <input type="text" class="form-control" placeholder="Aadhar Number" name="aadhar-no" value="{{user.aadhar_no}}">
    <input type="submit" value="Ok">
  </form>
  <form method="post" action="{% url 'RegistrationApp:save-update-details' %}">
    {% csrf_token %}
    <input type="text" class="form-control" placeholder="Aadhar Number" name="aadhar-no" value="{{user.aadhar_no}}" hidden>
    <input type="text" style="margin-bottom: 15px" class="form-control" placeholder="Full Name" name="full-name" value="{{user.full_name}}">
    <input type="date" style="margin-bottom: 15px" class="form-control" placeholder="Date Of Birth" name="dob" value="{{user.date_of_birth}}">
    <input type="text" class="form-control" placeholder="Phone Number" name="phone-no" value="{{user.phone_no}}">
    <input type="text" style="margin-bottom: 15px" class="form-control" placeholder="Country" name="country" value="{{user.country}}">
    <input type="text" class="form-control" placeholder="State" name="state" value="{{user.state}}">
    <input type="text" style="margin-bottom: 15px" class="form-control" placeholder="City" name="city" value="{{user.city}}">
    <input type="text" class="form-control" placeholder="Taluka" name="taluka" value="{{user.taluka}}">
    <input type="submit" value="update" style="display: block;margin: auto;margin-top: 10px" class="btn btn-success">
  </form>
  {% else %}
  <form method="post" action="{% url 'RegistrationApp:ok' %}">
    {% csrf_token %}
    <input type="text" class="form-control" placeholder="Aadhar Number" name="aadhar-no">
    <input type="submit" style="display: block;margin: auto;margin-top: 10px" class="btn btn-success" value="Ok">
  </form>

  {% endif %}
</div>
{% endblock %}

templates/voter-profile-login.html
{% extends 'base.html' %}
{% block content %}

  <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" style="font-weight: 900;">Voter Profile Login</a>
      <a class="btn btn-success" href="{% url 'CryptoBallotsHomeApp:home' %}">Home</a>
  </nav>
  <div style="padding: 20px;width: 300px;background-color: #fe6e00;display: block;margin: auto;
    margin-top: 250px">
    <h1 style="color: white;text-align: center">Voter Profile</h1>
    <form method="post" action="{% url 'VoterProfileApp:voter-login-success' %}">
      {% csrf_token %}
      <input type="text" style="margin-bottom: 15px" class="form-control" placeholder="VoterID" name="voter-id">
      <input type="password" class="form-control" placeholder="password" name="password">
      <input type="submit" style="display: block;margin: auto;margin-top: 10px" class="btn btn-success" >
    </form>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

  </div>
  <a class="btn btn-success" href="{% url 'VoterProfileApp:forgot-password' %}">Forgot password</a>


{% endblock %}

templates/voter-profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" style="font-weight: 900;">{{name}}</a>
    <a class="btn btn-danger" href="{% url 'VoterProfileApp:voter-logout' %}">Logout</a>
</nav>
<h1 style="color: Black;text-align: center;margin-top: 30px">Profile</h1>
<div style="padding: 20px;width: 800px;background-color: #fe6e00;display: block;margin: auto">
  <h1 style="color: white;text-align: center">Name: {{name}}</h1>
  <h1 style="color: white;text-align: center">Username:  {{username}}</h1>
  <h1 style="color: white;text-align: center">VoterId:  {{voter_id}}</h1>
  <h1 style="color: white;text-align: center">Aadhar Number:  {{aadhar_no}}</h1>
  <h1 style="color: white;text-align: center">Mobile Number:  {{phone_no}}</h1>
  <h1 style="color: white;text-align: center">Date Of Birth:  {{date_of_birth}}</h1>
  <h1 style="color: white;text-align: center">Age:  {{age}}</h1>
  <h1 style="color: white;text-align: center">Country:  {{country}}</h1>
  <h1 style="color: white;text-align: center">State:  {{state}}</h1>
  <h1 style="color: white;text-align: center">city:  {{city}}</h1>
  <h1 style="color: white;text-align: center">Taluka:  {{taluka}}</h1>
  <h1 style="color: white;text-align: center">pincode:  {{pincode}}</h1>
  <h1 style="color: white;text-align: center">constituency:  {{constituency}}</h1>
  <h1 style="color: white;text-align: center">Voting Stars:  {{voting_stars}}</h1>
  <img src="{{image.url}}" alt="dp2">
</div>
<a class="btn btn-danger" href="{% url 'VoterProfileApp:changepassword' %}">Change Password</a>
{% endblock %}

templates/voting-window.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" style="font-weight: 900;">Voting Window</a>
    <a class="btn btn-danger" href="{% url 'VotingApp:logout' %}">Logout</a>
</nav>

<div style="padding: 20px;width: 800px;background-color: #fe6e00;display: block;margin: auto;
  margin-top: 80px">
  <h1 style="color: white;text-align: center">Vote</h1>
  {% if more_details %}
  <form method="post" action="{% url 'VotingApp:display-candidates' %}">
    {% csrf_token %}
    <input type="text" style="margin-bottom: 15px" class="form-control" placeholder="voting-id" name="voting-id" value='{{voter_id}}'>
    <input type="submit" style="margin-bottom: 15px" class="form-control" name="submit">
  </form>

  <form method="POST" action="{% url 'BlockchainApp:route_wallet_transact' %}">
    {% csrf_token %}
  {% for candidate in candidates %}
    <input type="radio" id="selected_candidate" name="selected_candidate" value="{{candidate.user.aadhar_no}}">
    <label for="selected_candidate"><b>Name : </b>{{candidate.user.username}} <b>Candidate party:</b>{{candidate.party}}</label>
    <br>
  {% endfor %}
    <input type="submit" name="Vote" value="Vote">
  </form>
  {% else %}
  <form method="post" action="{% url 'VotingApp:display-candidates' %}">
    {% csrf_token %}
    <input type="text" style="margin-bottom: 15px" class="form-control" placeholder="voting-id" name="voting-id">
    <input type="submit" style="margin-bottom: 15px" class="form-control" name="submit">
  </form>
  {% endif %}
</div>
{% endblock %}